-- V1__create_user_tables.sql
-- Auth, user and notification tables (owned by M4)

CREATE TABLE users (
    user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name           VARCHAR(100)  NOT NULL,
    email               VARCHAR(120)  NOT NULL UNIQUE,
    password            VARCHAR(255),
    role                VARCHAR(20)   NOT NULL DEFAULT 'ROLE_USER'
                            CHECK (role IN ('ROLE_ADMIN','ROLE_TECHNICIAN','ROLE_USER')),
    provider            VARCHAR(20)   NOT NULL DEFAULT 'LOCAL'
                            CHECK (provider IN ('LOCAL','GOOGLE','FACEBOOK')),
    provider_id         VARCHAR(120),
    profile_picture_url VARCHAR(500),
    phone_number        VARCHAR(20)   UNIQUE,
    enabled             BOOLEAN       NOT NULL DEFAULT true,
    email_verified      BOOLEAN       NOT NULL DEFAULT false,
    last_login_at       TIMESTAMP,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    token      VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP    NOT NULL,
    used       BOOLEAN      NOT NULL DEFAULT false,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password_reset_otps (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    otp        VARCHAR(10) NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    used       BOOLEAN     NOT NULL DEFAULT false,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    type            VARCHAR(50)   NOT NULL
                        CHECK (type IN ('BOOKING_UPDATE','TICKET_UPDATE','COMMENT')),
    title           VARCHAR(180)  NOT NULL,
    message         VARCHAR(1000) NOT NULL,
    read            BOOLEAN       NOT NULL DEFAULT false,
    action_url      VARCHAR(255),
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email           ON users (email);
CREATE INDEX idx_users_role            ON users (role);
CREATE INDEX idx_notifications_user_id ON notifications (user_id);
CREATE INDEX idx_notifications_read    ON notifications (read);
