-- V2__create_resource_booking_tables.sql
-- Resource and booking tables (owned by M1 and M2)

CREATE TABLE resource (
    resource_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(200) NOT NULL,
    type               VARCHAR(50)  NOT NULL
                           CHECK (type IN ('LAB','ROOM','EQUIPMENT')),
    capacity           INT          NOT NULL DEFAULT 0,
    location           VARCHAR(200),
    availability_start TIME,
    availability_end   TIME,
    status             VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                           CHECK (status IN ('ACTIVE','OUT_OF_SERVICE')),
    description        TEXT,
    image_url          VARCHAR(500)
);

CREATE TABLE booking (
    booking_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"      BIGINT       NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    "resourceID"  BIGINT       NOT NULL REFERENCES resource (resource_id) ON DELETE CASCADE,
    date          DATE         NOT NULL,
    start_time    TIME         NOT NULL,
    end_time      TIME         NOT NULL,
    purpose       VARCHAR(500),
    attendees     INT          NOT NULL DEFAULT 1,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                      CHECK (status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
    reject_reason VARCHAR(500),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_resource_type   ON resource (type);
CREATE INDEX idx_resource_status ON resource (status);
CREATE INDEX idx_booking_user    ON booking ("userId");
CREATE INDEX idx_booking_resource ON booking ("resourceID");
CREATE INDEX idx_booking_status  ON booking (status);
CREATE INDEX idx_booking_date    ON booking (date);
