spring.application.name=server
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/smartcampus
spring.datasource.username=smartcampus
spring.datasource.password=smartcampus
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartcampus12345@gmail.com
spring.mail.password=slfsecaayoassegc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#JWT 
app.jwt.secret=yourSuperSecretKeyThatIsAtLeast32CharactersLong123
app.jwt.expiration-ms=86400000

app.oauth2.authorizedRedirectUri=http://localhost:5173/oauth2/redirect

spring.security.oauth2.client.registration.google.client-id=301007095241-08h961r5lb77cdg8qmj0i41nf0f0j555.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=YOUR_SECRET_HERE
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# spring.security.oauth2.client.registration.facebook.client-id=
# spring.security.oauth2.client.registration.facebook.client-secret=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

