spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5432/smartcampus
spring.datasource.username=smartcampus
spring.datasource.password=smartcampus
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartcampus12345@gmail.com
spring.mail.password=slfsecaayoassegc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#JWT
app.jwt.secret=yourSuperSecretKeyThatIsAtLeast32CharactersLong123
app.jwt.expiration-ms=86400000

app.firebase.credentials-path=src/main/resources/firebase-key.json

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

app.file.upload-dir=uploads
