services:
  postgres:
    image: "postgres:17"
    container_name: smartcampus_db
    environment:
      POSTGRES_DB: smartcampus
      POSTGRES_USER: smartcampus
      POSTGRES_PASSWORD: smartcampus
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
